[pytest]
DJANGO_SETTINGS_MODULE = core.settings.test
python_files = tests.py test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = -p no:selenium -m "not e2e"
markers =
    e2e: testes Selenium com frontend em execução (pytest -m e2e para rodar)